source "$HOME/.config/bash/utils"
source "$HOME/.config/bash/promptrc"

export EDITOR=nvim
export GOPATH=$HOME/.go
export LESS='-R --use-color -Dd+y$Du+b$'
export MANPAGER='less -R --use-color -Dd+y -Du+b'
export MANROFFOPT='-P -c'

prepend_path_if "$HOME/.local/go/bin"
prepend_path_if "$GOPATH/bin"

prepend_path_if "$HOME/.local/zig"

alias cp='cp -i'
alias mv='mv -i'

[[ -d ~/.config/nvim-minimal ]] && alias vi='NVIM_APPNAME=nvim-minimal nvim'

if [[ -f /etc/os-release ]]; then
    source /etc/os-release
elif [[ -f /usr/lib/os-release ]]; then
    source /usr/lib/os-release
fi

source_if ~/.config/bash/"bashrc.${ID:-linux}"
source_if ~/.config/bash/"bashrc.${HOSTNAME}"
