%hidden BG1=#3c3836
%hidden FG1=#ebdbb2
%hidden FG2=#d5c4a1

# Set a Ctrl-b shortcut for reloading your tmux config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded config"

# Change prefix to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Remove annoying Esc behaviour
set -s escape-time 0

set -g default-terminal 'tmux-256color'

# tell Tmux that outside terminal supports true color
set -as terminal-overrides ',*256col*:Tc'
set -as terminal-overrides ',alacritty:Tc'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Set vi keys
setw -g mode-keys vi

# Capture mouse events
set -g mouse on

# Set vi like copy-paste behaviour
unbind [
bind Escape copy-mode
unbind C-p
bind C-p paste-buffer

# Bind <prefix>c, <prefix>", and <prefix>% to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# vim copy mode
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
unbind-key -T copy-mode-vi MouseDragEnd1Pane

# move windows left and right with <prefix>-h and <prefix>-l
unbind-key h
unbind-key l
bind-key h swap-window -d -t -1
bind-key l swap-window -d -t +1

# rebind last window to <prefix>-k (since <prefix>-l was rebound above)
bind-key k last-window

set -g set-titles 'on'
set -g set-titles-string '(#S:#I) #W@#T #{session_alerts}'

# default statusbar color
set-option -g status-style bg=$BG1,fg=$FG1

# pane border
set-option -g pane-active-border-style "#{?pane_in_mode,fg=yellow,#{?synchronize-panes,fg=red,fg=$FG2}}"
set-option -g pane-border-style fg=$BG1

# vim aware pane navigation
vim_pattern='(\S+\/)?n?vim?(diff)?$'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ]+ +$vim_pattern'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' {if -F '#{pane_at_left}' '' 'select-pane -L'}
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' {if -F '#{pane_at_bottom}' '' 'select-pane -D'}
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' {if -F '#{pane_at_top}' '' 'select-pane -U'}
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' {if -F '#{pane_at_right}' '' 'select-pane -R'}

bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
